BEIMA.Backend.Test/BEIMA.Backend.Test.csproj, BEIMA.Backend.Test/Function1Test.cs, BEIMA.Backend.Test/SampleDBTest.cs, BEIMA.Backend.Test/SampleFileStoreTest.cs, BEIMA.Backend.Test/SampleFunctionTest.cs, BEIMA.Backend/BEIMA.Backend.sln
Set up the framework for adding unit tests to the code. I have set up some sample tests using different variations of "Assert" as examples for each of the classes. Right now they should all just pass no matter what.
=> Add Unit Testing

.github/workflows/beima.yml, build.sh, test.sh
Closes #41
Commands needed for React code and React tests. 
Resources used to figure these out:
https://github.com/facebook/create-react-app/issues/11043
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04
=> Adding commands to build and test scripts for React testing

.github/ISSUE_TEMPLATE/1-task.md, .github/ISSUE_TEMPLATE/2-bug.md, .github/ISSUE_TEMPLATE/3-user-story.md, .github/ISSUE_TEMPLATE/4-epic.md, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
#37
copied the templates that Professor Dit added to our 471 repo into the same location.
based on what I read and placement in the other repo these should then show up as options when creating a new issue
=> added templates from 471

.github/CODEOWNERS
Closes #40
don't mind the branch name
=> added codeowners file which should flag everyone for reviews on PR

BEIMA.Backend.Test/Function1Test.cs, test.sh
Closes #34
Added in backend unit tests to the test script.
=> Make test script run unit tests

build.sh
Closes #58
I realized we haven't added actual build commands yet into our build.sh file. I've added a command to build all backend projects and build our client as well
=> Adding build commands for both backend and client

.github/workflows/beima.yml, BEIMA.Backend.FT/BEIMA.Backend.FT.csproj, BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/FunctionalTestBase.cs, BEIMA.Backend.FT/SampleFT.cs, BEIMA.Backend/BEIMA.Backend.sln, build.sh, test.sh
Closes #53
Implemented the backend FT framework. Included is an http client class to allow us to interface with the running backend instance. Additionally I have included a sample functional test class.
=> Setup ft framework

.github/workflows/beima.yml
Closes #62
Closes #63 
Closes #64
Closes #65
This is a modification to the beima.yml GitHub Action. I am adding in these environment variables because these are necessary for the backend to run properly. Without it, my tests will fail.
=> Added environment variables

build.sh
Closes #72 
Added MongoDB to the build.sh file.
=> Added MongoDB to build.sh

docs/minutes.md
Proposed sprint objective for sprint 0
=> updated minutes with sprint 0 objective

.github/workflows/beima.yml
=> changing actions to pr and ignore docs folder

.gitignore, BEIMA.Client/cypress/integration/Router.spec.js, BEIMA.Client/package-lock.json, BEIMA.Client/package.json, BEIMA.Client/src/App.js, BEIMA.Client/src/pages/Help/HelpPage.js, BEIMA.Client/src/pages/Home/HomePage.css, BEIMA.Client/src/pages/Home/HomePage.js
Closes #104 
Setups up initial router component
=> Added initial router plus tests

.github/workflows/beima.yml, build.sh
=> More workflow changes

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.FT/FunctionalTestBase.cs, BEIMA.Backend.Test/BEIMA.Backend.Test.csproj, BEIMA.Backend.Test/DeviceTest.cs, BEIMA.Backend.Test/MongoService/MongoConnectorTest.cs, BEIMA.Backend.Test/RequestFactory.cs, BEIMA.Backend.Test/UnitTestBase.cs, BEIMA.Backend/BEIMA.Backend.sln, BEIMA.Backend/Device.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/MongoService/MongoConnector.cs, BEIMA.Backend/MongoService/MongoDefinition.cs
Closes #98
Adds functionality to retrieve a device from the database using an id from a query string
=> Add device get functionality and tests

BEIMA.Client/staticwebapp.config.json
=> Fix Azure Client Routing 404

BEIMA.Client/src/App.css, BEIMA.Client/src/shared/PageTitle.js, BEIMA.Client/src/shared/shared.css
Closes #115
I thought the nav bar grew too much when the page got bigger, so I set a max width and let the content of the page grow. I also added some autocapitalization for the page titles.
=> CSS improvements and autocapitalization for shared components

docs/Coding Standards/C#_JavaScript_Standards.md, docs/Coding Standards/C#_Unit_Test_Standards.md
Closes #70 
Closes #71
I had some down time and thought I'd get a start on documenting the coding standards we have been discussing over the weeks. When these are approved, I will also add them to our Wiki page.
=> Adding coding and unit test standards

.gitignore, BEIMA.Client/package-lock.json, BEIMA.Client/package.json
Closes #124
Added 'dotenv' npm package to handle environment variables through the Node server
Added the base .env file to the .gitignore so that it will not be checked in
=> added dotenv, Node env var handler

build.sh
Fixes failing frontend tests on main
=> Fixes to frontend test failures on main

BEIMA.Backend.Test/MongoService/DeviceTypeTest.cs, BEIMA.Backend/MongoService/DeviceType.cs
Closes #111
This PR implements a POCO for DeviceType.
=> Create POCO for DeviceType

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.Test/DeviceFunctions/UpdateDeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceFunctions/UpdateDevice.cs, BEIMA.Backend/MongoService/IMongoConnector.cs
Closes #100 
Implements device update endpoint.
=> Device update endpoint

docs/Initial Setup/InitialSetup.md
Closes #148
Short setup guide for new developers to follow to set up their environment
Suggested changes welcome
=> added doc for initial setup for development

BEIMA.Client/src/services/DeleteDevice.js
Closes #96
calling with valid device deletes it from the DB
calling with an invalid device returns status 400 and "Bad Request" from the API
=> Delete Device API call

BEIMA.Backend/DeviceFunctions/AddDevice.cs, BEIMA.Client/src/services/AddDevice.js
Closes #92
A JSON object can be passed to be saved in the DB
=> Add Device API call

BEIMA.Backend.Test/DeviceFunctions/GetDeviceTest.cs, BEIMA.Backend/DeviceFunctions/GetDevice.cs, test.sh
Closes #191 
Just needed to cleanup and add more tests in for get device. I established a bit of a standard with the other device endpoints after implementing this one first and I would like to match the GET endpoint up with those.
=> GET device endpoint and test cleanup

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/DeviceTypeFunctions/AddDeviceTypeTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceTypeFunctions/AddDeviceType.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Rules.cs
=> Add device type POST endpoint

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.Test/DeviceTypeFunctions/GetDeviceTypeTest.cs, BEIMA.Backend/DeviceFunctions/GetDeviceList.cs, BEIMA.Backend/DeviceTypeFunctions/AddDeviceType.cs, BEIMA.Backend/DeviceTypeFunctions/GetDeviceType.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx
=> Device type GET endpoint

BEIMA.Client/src/services/AddDeviceType.js
Closes #181
Added API call for Add Device Type.
=> Added Add Device Type endpoint call

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.Test/DeviceTypeFunctions/GetDeviceTypeListTest.cs, BEIMA.Backend/DeviceTypeFunctions/GetDeviceTypeList.cs, BEIMA.Backend/MongoService/IMongoConnector.cs
Closes #179 
FT is marked explicit until I can implement the delete endpoint.
=> Device type getlist endpoint

BEIMA.Client/src/pages/Devices/DevicesPage.js, BEIMA.Client/src/shared/ItemList/ItemList.js
Closes #170 
There is still some more work needed for this page, but that is related to Milestone 4. It still needs building and device type info.  And there might be a need for a method to combine all of the device, building, and device type data together. These changes satisfy the ability to view a list of devices
https://user-images.githubusercontent.com/58532471/156939499-2ff29888-ba4b-4bb7-90f7-102e1c4f7c5d.mp4
=> Adding device list api call to device list page

BEIMA.DB.Schemas/device-schema.txt, BEIMA.DB.Schemas/device-type-schema.txt
Closes #185 
Made changes to the device schema to allow for photos and files to be stored. Also added some notes from a previous discussion we had about what will be sent from the front end to the back end for device type creation.
=> Add photos and files to device schema

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.Test/DeviceTypeFunctions/DeleteDeviceTypeTest.cs, BEIMA.Backend/DeviceTypeFunctions/DeleteDeviceType.cs, BEIMA.Backend/MongoService/IMongoConnector.cs
=> Device type delete endpoint

BEIMA.Backend.Test/MongoService/DeviceTest.cs, BEIMA.Backend/MongoService/Device.cs
Closes #186 
Closes #187
Closes #184 - story
This PR implements photos/files functionality in the Device POCO. It also updates the unit tests to include these fields as part of its testing procedures.
=> Update Device POCO to add photos and files

BEIMA.Client/src/services/GetDeviceTypeList.js
Closes #90 
Since this is for the list view, I am filtering out the fields for a device type
=> Device Type list js code

BEIMA.Client/src/services/GetDeviceType.js
=> Get individual device type js code

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/DeviceTypeFunctions/UpdateDeviceTypeTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceTypeFunctions/UpdateDeviceType.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/MongoService/MongoConnector.cs, BEIMA.Backend/Rules.cs
=> Device type update endpoint

.github/workflows/beima.yml, BEIMA.Client/cypress/integration/AddDeviePage.spec.js, BEIMA.Client/src/pages/Devices/AddDevicePage.js, BEIMA.Client/src/shared/FormList/FormList.js, BEIMA.Client/src/shared/FormList/FormListWithErrorFeedback.js, package-lock.json, package.json
Closes #164 
If an invalid entry is present it will be flagged when clicking "Add Device"
=> Add lat lon validation

BEIMA.Client/cypress/integration/AddDeviceTypePage.spec.js, BEIMA.Client/src/pages/DeviceTypes/AddDeviceTypePage.js
Closes #169 
Added add device type api call to the add device type page. I also added some input validation for custom fields. This makes it so the user can't add empty fields or a field that is already added. 
https://user-images.githubusercontent.com/58532471/157730401-da13d013-0f68-42d1-afc9-26be5382f283.mp4
=> Add device type page api

BEIMA.DB.Schemas/database-and-collection-names.txt, BEIMA.DB.Schemas/user-schema.txt
Closes #229 
This PR implements the User database schema.
I also added a file that details what DB name and collection names we are using.
=> Create schema for User

.gitignore
Didn't make a task since this is so small, but in order to run test.sh locally, we need the Minio folders created. Added Minio to the gitignore
=> Adding minio to gitignore

BEIMA.Backend.Test/MongoService/BuildingTest.cs, BEIMA.Backend/MongoService/Building.cs
Closes #112 
This PR implements a POCO for Building. It also implements the relevant unit tests as well.
=> Create POCO for Building

BEIMA.Backend.Test/MongoService/UserTest.cs, BEIMA.Backend/MongoService/User.cs, BEIMA.DB.Schemas/user-schema.txt
Closes #113 
This PR implements a POCO for User, as well as the relevant unit tests.
=> Create POCO for User

BEIMA.Client/cypress/integration/AddBuildingPage.spec.js, BEIMA.Client/src/App.js, BEIMA.Client/src/pages/Building/AddBuildingPage.js, BEIMA.Client/src/pages/Building/AddBuildingPage.module.css
Closes #240 
Created an add building page, it's pretty simple. Currently, can only access it via the url, but I'm planning to have a button on the building list page that navigates the user to this page.
=> Creating add building page

.github/workflows/beima.yml, BEIMA.Backend.Test/MongoService/MongoConnectorTest.cs, BEIMA.Backend/MongoService/MongoConnector.cs
Closes #182 
This PR implements MongoConnector functionality for Building. It also implements the relevant unit tests and adds a new environment variable.
=> Implement Building MongoConnector Functionality

.github/workflows/beima.yml, BEIMA.Backend.Test/MongoService/MongoConnectorTest.cs, BEIMA.Backend.Test/UnitTestBase.cs, BEIMA.Backend/MongoService/MongoConnector.cs
Closes #183
Closes #255 
This PR implements MongoConnector functionality for Users. This PR also includes unit tests, adds an environment variable, and updates the UnitTestBase class to include the new POCOs.
=> Implement User MongoConnector Functionality

BEIMA.Client/src/services/UpdateDeviceType.js
Closes #200
rebranched, maybe the base was main on accident the first time
=> added update device type

BEIMA.Client/cypress/integration/DeviceTypesPage.spec.js, BEIMA.Client/cypress/integration/Router.spec.js
=> Adding skipOn to problem test

.github/workflows/beima.yml, BEIMA.Client/cypress/integration/AddBuildingPage.spec.js, BEIMA.Client/cypress/integration/AddDevicePage.spec.js, BEIMA.Client/cypress/integration/AddDeviceTypePage.spec.js, BEIMA.Client/cypress/integration/DevicePage.spec.js, BEIMA.Client/cypress/integration/DeviceTypesPage.spec.js, BEIMA.Client/cypress/integration/Router.spec.js, build.sh, test.sh
Closes #221
RIP cypress tests from workflow
The failing test is from issue #269
=> removing cypress tests from workflow

BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.Test/DeviceFunctions/AddDeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceFunctions/AddDevice.cs
Closes #188
Makes sure that an added device is compatible with its device type.
=> Add device now compatible with device type

BEIMA.Backend.Test/DeviceFunctions/UpdateDeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceFunctions/AddDevice.cs, BEIMA.Backend/DeviceFunctions/UpdateDevice.cs
=> Device update integrated with device type fields

docs/Initial Setup/InitialSetup.md
Closes #311
I added instructions for completing the mongo setup in MongoCompass.
I'm not sure if I captured them all since it was a while ago (and via docker on a separate machine) that I set it up so correct/add as needed!
=> updated initial dev setup with MongoDB install instructions

BEIMA.Client/src/pages/Building/AddBuildingPage.js
Closes #319
added import and updated references
=> added consts import and updated references

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/BuildingFT.cs, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/BuildingFunctions/AddBuildingTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/BuildingFunctions/AddBuilding.cs, BEIMA.Backend/DeviceFunctions/AddDevice.cs, BEIMA.Backend/Models/Requests.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Rules.cs
=> Building POST endpoint

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/DeviceFunctions/UpdateDeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceFunctions/UpdateDevice.cs, BEIMA.Backend/MongoService/Device.cs
Closes #232 
References #233 
Adds storage capabilities to update device endpoint
=> Added storage to update endpoint

BEIMA.Client/package-lock.json, BEIMA.Client/package.json, BEIMA.Client/src/shared/Notifications/Notification.js, BEIMA.Client/src/shared/Notifications/Notification.module.css
Closes #315
Added SweetAlert2 package and simplified the 3 main calls we'll use (success, warning, error) through the Notifications.js file to take care of the common parameters without having to from the whole message each time
=> Task 315 - shared components for notifications

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/BuildingFT.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/BuildingFunctions/GetBuildingListTest.cs, BEIMA.Backend/BuildingFunctions/GetBuildingList.cs, BEIMA.Backend/MongoService/Building.cs, BEIMA.Backend/MongoService/DeviceType.cs, BEIMA.Backend/MongoService/IMongoConnector.cs
Closes #288
Implements the endpoint for building get list.
=> Task288 building get list endpoint

BEIMA.Client/src/services/GetBuildingList.js
Closes #309
Added JS call to get the building list and filtered the fields down to only what's used on the Building List page
=> Task 309 Get building list JS call

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/BuildingFT.cs, BEIMA.Backend.Test/BuildingFunctions/DeleteBuildingTest.cs, BEIMA.Backend/BuildingFunctions/DeleteBuilding.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx
Closes #290
Adds the building delete endpoint.
=> Building delete endpoint

BEIMA.Backend.Test/MongoService/MongoConnectorTest.cs, BEIMA.Backend/MongoService/MongoConnector.cs
Closes #339 
This PR implements filtering for Building objects in the MongoConnector.
=> Implement filtering for Building in MongoConnector

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/BuildingFT.cs, BEIMA.Backend.Test/BuildingFunctions/UpdateBuildingTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/BuildingFunctions/AddBuilding.cs, BEIMA.Backend/BuildingFunctions/UpdateBuilding.cs, BEIMA.Backend/Models/Requests.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/MongoService/MongoConnector.cs
Closes #289
Implements the update building endpoint with associated tests.
=> Update building endpoint

BEIMA.Client/src/pages/DeviceTypes/AddDeviceTypePage.js, BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js, BEIMA.Client/src/pages/Devices/AddDevicePage.js, BEIMA.Client/src/pages/Devices/DevicePage.js
Closes #355 
Added some success and error messages for adding/updating a device/device type. I've attached screenshots of the success, but the error will look similar, and will hopefully not be encountered that much.
=> Add update/add success and error messages to devices/device types

BEIMA.Client/src/services/GetBuilding.js
Closes #310
Gets the data for a single building when provided the Building ID.
All data is returned, but last modified data can be filtered off if needed
=> created JS db call for single building

.github/workflows/deploy-backend.yaml, .github/workflows/deploy-client.yaml, BEIMA.Client/README.md
Closes #375
Adds another env variable to cause the deploy step to set the backend api for the cloud frontend. Also adds workflow dispatching for the other actions.
=> Set backend api in deploy step

BEIMA.Client/cypress/integration/DeviceTypesPage.spec.js
Closes #269
based test on classes that have a name that starts with "ItemList_item" and count the results
when at least one device exists in the DB there will be (minimum) 2 divs with the specified CSS identifier
=> Task#269 device type list test fails

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/UserFunctions/GetUserTest.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/UserFunctions/GetUser.cs
Closes #303
This PR implements the GetUser endpoint.
=> User GET - GetUser

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/UserFunctions/GetUserListTest.cs, BEIMA.Backend/BuildingFunctions/GetBuildingList.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/MongoService/User.cs, BEIMA.Backend/UserFunctions/GetUserList.cs
Closes #304 
This PR implements the GetUserList endpoint.
=> User GET - GetUserList

BEIMA.Client/src/services/AddUser.js, BEIMA.Client/src/services/DeleteUser.js, BEIMA.Client/src/services/GetUser.js, BEIMA.Client/src/services/GetUserList.js, BEIMA.Client/src/services/UpdateUser.js
Closes #283
Closes #285 
Currently, the add/get user endpoints are done, but these JS service functions are really simple to create. I got all of them created here, but we will need to wait to merge/test these when all the endpoints are done.
=> User JS service functions

BEIMA.Backend.FT/AuthFT.cs, BEIMA.Backend.FT/BEIMA.Backend.FT.csproj, BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/AuthFunctions/LoginTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/AuthFunctions/Login.cs, BEIMA.Backend/AuthService/AuthenticationService.cs, BEIMA.Backend/Models/Requests.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx
Closes #377
Implements a login endpoint that takes in a username and password, checks if a user has those credentials, and then returns a jwt token based on the found user. If the request parameters are invalid or the user doesn't exist, throws a 401 unauthorized.
=> 377 Login Endpoint

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/UserFunctions/DeleteUserTest.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/UserFunctions/DeleteUser.cs
Closes #306 
This PR implements the DeleteUser endpoint.
=> User POST - DeleteUser

BEIMA.Backend.FT/BEIMA.Backend.FT.csproj, BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend.Test/UserFunctions/GetUserTest.cs, BEIMA.Backend.Test/UserFunctions/UpdateUserTest.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/UserFunctions/UpdateUser.cs
Closes #305
This PR implements the UpdateUser endpoint.
=> User POST - UpdateUser

BEIMA.Backend.Test/RulesTest.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/Rules.cs
Closes #295
This helps to add field validation to the backend for buildings.
=> Building backend validation

BEIMA.Backend.Test/RulesTest.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/Rules.cs, BEIMA.Backend/UserFunctions/AddUser.cs
Closes #296
This adds validation for user fields when a user is generated.
=> User backend validation

BEIMA.Client/src/Constants.js, BEIMA.Client/src/pages/Users/AddUserPage.js, BEIMA.Client/src/pages/Users/AddUserPage.module.css, BEIMA.Client/src/pages/Users/ListUsersPage.js, BEIMA.Client/src/pages/Users/UserPage.js, BEIMA.Client/src/services/GetUser.js, BEIMA.Client/src/services/GetUserList.js
Closes #284 
I've integrated the User service functions into their appropriate pages. Right now, the add user works, we will need to wait for the rest of the endpoints to confirm the integrations works. Wanted to get it up for review though for any possible feedback. I am confident that there won't be much more to change once the endpoints are done. I will also post a demo video once the endpoints are done.
=> User service integration into User pages

BEIMA.Backend.Test/MongoService/MongoFilterGeneratorTest.cs, BEIMA.Backend/MongoService/MongoFilterGenerator.cs
Closes #399
This PR implements OR filter functionality to the MongoFilterGenerator. The "CombineFilters" method was also renamed to AndFilters().
=> Add OR filtering to MongoFilterGenerator

BEIMA.Backend.FT/AuthFT.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend.Test/UserFunctions/AddUserTest.cs, BEIMA.Backend.Test/UserFunctions/UpdateUserTest.cs, BEIMA.Backend/Constants.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/UserFunctions/AddUser.cs, BEIMA.Backend/UserFunctions/UpdateUser.cs
Closes #395 
This adds validation for passwords on the backend to make sure they fulfill our requirements for passwords.
=> Add backend password requirement validation

test.sh
Closes #103
This PR is attempting to eliminate the 20 second wait time for the backend API to start.
=> Remove 20 second wait time

BEIMA.Backend.Test/BuildingFunctions/DeleteBuildingTest.cs, BEIMA.Backend/BuildingFunctions/DeleteBuilding.cs, BEIMA.Client/src/pages/Building/AddBuildingPage.js, BEIMA.Client/src/pages/Building/BuildingListPage.js, BEIMA.Client/src/pages/Building/BuildingPage.js, BEIMA.Client/src/pages/Devices/DevicePage.js, BEIMA.Client/src/pages/Devices/DevicesPage.js, BEIMA.Client/src/services/AddBuilding.js, BEIMA.Client/src/services/DeleteBuilding.js, BEIMA.Client/src/services/UpdateBuilding.js, BEIMA.Client/src/shared/ItemList/ItemList.js
Closes #423 
Closes #424 
Closes #425
Closes #426 
Got the rest of the building integration done. We can now add/update/delete/view buildings. I also updated the device pages to show building information as well. As always, here's a demo
https://user-images.githubusercontent.com/58532471/162265303-4ca9e2ca-9dba-4289-9402-d12642f62f8d.mp4
=> Building integration

BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js
=> Adding the rest of the mandatory fields to device type view

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/ReportFT.cs, BEIMA.Backend.Test/ReportFunctions/AddDevicesReportTest.cs, BEIMA.Backend/ReportFunctions/AllDevicesReport.cs
Closes #397
This is the endpoint for returning the all devices report in a zip file.
=> All devices report endpoint

BEIMA.Client/src/pages/Devices/AddDevicePage.js, BEIMA.Client/src/pages/Devices/DevicePage.js, BEIMA.Client/src/shared/Notifications/Notification.js
Closes #356
added notification for mult-line warnings
updated device page to send single string instead of array
changed Add Device page to use the multi line warning message
=> Task#356 upgrade notification js for single warning

BEIMA.Client/src/App.js, BEIMA.Client/src/services/AddBuilding.js, BEIMA.Client/src/services/AddDevice.js, BEIMA.Client/src/services/AddDeviceType.js, BEIMA.Client/src/services/AddUser.js, BEIMA.Client/src/services/Authentication.js, BEIMA.Client/src/services/DeleteBuilding.js, BEIMA.Client/src/services/DeleteDevice.js, BEIMA.Client/src/services/DeleteDeviceType.js, BEIMA.Client/src/services/DeleteUser.js, BEIMA.Client/src/services/GetBuilding.js, BEIMA.Client/src/services/GetBuildingList.js, BEIMA.Client/src/services/GetDevice.js, BEIMA.Client/src/services/GetDeviceList.js, BEIMA.Client/src/services/GetDeviceType.js, BEIMA.Client/src/services/GetDeviceTypeList.js, BEIMA.Client/src/services/GetUser.js, BEIMA.Client/src/services/GetUserList.js, BEIMA.Client/src/services/UpdateBuilding.js, BEIMA.Client/src/services/UpdateDevice.js, BEIMA.Client/src/services/UpdateDeviceType.js, BEIMA.Client/src/services/UpdateUser.js
Closes #368 
Closes #367 
Adding auth headers to all the JS services. I will update the calls to these function in this task #369.
=> Adding auth tokens to all JS service functions

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/BuildingFT.cs, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.FT/FunctionalTestBase.cs, BEIMA.Backend.Test/DeviceFunctions/AddDeviceTest.cs, BEIMA.Backend.Test/DeviceFunctions/DeleteDeviceTest.cs, BEIMA.Backend.Test/DeviceFunctions/GetDeviceListTest.cs, BEIMA.Backend.Test/DeviceFunctions/GetDeviceTest.cs, BEIMA.Backend.Test/DeviceFunctions/UpdateDeviceTest.cs, BEIMA.Backend/AuthFunctions/Login.cs, BEIMA.Backend/AuthService/AuthenticationDefinition.cs, BEIMA.Backend/DeviceFunctions/AddDevice.cs, BEIMA.Backend/DeviceFunctions/DeleteDevice.cs, BEIMA.Backend/DeviceFunctions/GetDevice.cs, BEIMA.Backend/DeviceFunctions/GetDeviceList.cs, BEIMA.Backend/DeviceFunctions/UpdateDevice.cs
Closes #405
Add authentication in front of all the device endpoints. Also updated the unit and functional tests to handle this change.
=> #405 Auth Device Endpoints

BEIMA.Backend.Test/AuthFunctions/LoginTest.cs, BEIMA.Backend.Test/AuthService/AuthenticationServiceTest.cs, BEIMA.Backend/AuthService/AuthenticationService.cs, BEIMA.Backend/Models/Claims.cs, BEIMA.Client/src/App.js, BEIMA.Client/src/pages/Authentication/LoginPage.js, BEIMA.Client/src/pages/Users/UserPage.js, BEIMA.Client/src/services/Authentication.js, BEIMA.Client/src/shared/NavBar.js
Closes #369 
Closes #370
Login page is now the landing page. Admin users only have access to the users page. A user can't delete themselves. And the remember me box works. I need to update the JS service functions to check for 401 response and log the user out if so, but I will do that in another task.
https://user-images.githubusercontent.com/58532471/163063050-04f799b3-6336-4288-a674-88bf2f504dbd.mp4
=> Auth integration into pages

BEIMA.Client/src/Constants.js, BEIMA.Client/src/services/AddBuilding.js, BEIMA.Client/src/services/AddDevice.js, BEIMA.Client/src/services/AddDeviceType.js, BEIMA.Client/src/services/AddUser.js, BEIMA.Client/src/services/DeleteBuilding.js, BEIMA.Client/src/services/DeleteDevice.js, BEIMA.Client/src/services/DeleteDeviceType.js, BEIMA.Client/src/services/DeleteUser.js, BEIMA.Client/src/services/GetBuilding.js, BEIMA.Client/src/services/GetBuildingList.js, BEIMA.Client/src/services/GetDevice.js, BEIMA.Client/src/services/GetDeviceList.js, BEIMA.Client/src/services/GetDeviceType.js, BEIMA.Client/src/services/GetDeviceTypeList.js, BEIMA.Client/src/services/GetUser.js, BEIMA.Client/src/services/GetUserList.js, BEIMA.Client/src/services/UpdateBuilding.js, BEIMA.Client/src/services/UpdateDevice.js, BEIMA.Client/src/services/UpdateDeviceType.js, BEIMA.Client/src/services/UpdateUser.js, BEIMA.Client/src/shared/NavBar.js
Closes #448 
When a request is made to the backend a 401 response (unauthorized) is returned, we auto logout the user
=> adding auto logout on 401 response

BEIMA.Backend.Test/DeviceFunctions/AddDeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/MongoService/Device.cs
=> Removed null year manufactured check

BEIMA.Client/src/pages/DeviceTypes/AddDeviceTypePage.js
=> add device type page added warning for blank fields

BEIMA.Client/src/pages/Devices/AddDevicePage.js
Closes #450
photo/document vars are no longer logged to the console on save
=> removed log statements

BEIMA.Client/cypress/integration/DevicesPage.spec.js, BEIMA.Client/package-lock.json, BEIMA.Client/package.json, BEIMA.Client/src/pages/Devices/DevicesPage.js, BEIMA.Client/src/pages/Devices/DevicesPage.module.css, BEIMA.Client/src/services/GetDeviceList.js, BEIMA.Client/src/shared/DropDown/FilledDropDown.js, BEIMA.Client/src/shared/DropDown/FilledDropDown.module.css, BEIMA.Client/src/shared/ItemList/ItemList.js
Closes #414
Closes #413 
Closes #412
Adds two dropdowns on the devices page in order to allow filtering of devices based on device type and building.
=> #414#413 filter model

test.sh
Closes #469
Redirects backend API output to null when the testing script is ran so that our testing output doesn't get flooded with api logs.
=> redirect api stdout to null

BEIMA.Client/src/pages/Authentication/LoginPage.js, BEIMA.Client/src/services/Authentication.js
Closes #454 
https://user-images.githubusercontent.com/58532471/163689691-9ca61cde-a2ee-4e08-a9b0-e4dace04e89f.mp4
=> Adding error message for failed login attempt

BEIMA.Backend.FT/ReportFT.cs, BEIMA.Backend.Test/ReportFunctions/AddDevicesReportTest.cs, BEIMA.Backend/ReportFunctions/AllDevicesReport.cs
Closes #473
This adds authentication to the all devices report endpoint.
=> Add device report authentication

BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.Test/DeviceTypeFunctions/GetDeviceTypeListTest.cs, BEIMA.Backend/DeviceTypeFunctions/GetDeviceTypeList.cs
Closes #467
Adds count to the return object for the GetDeviceTypeList endpoint.
=> Add count to return object for GetDeviceTypeList endpoint

BEIMA.Client/src/pages/Devices/AddDevicePage.js
Closes #479 
Added location notes to the form and updated the create JSON function to trim the field name down to just "notes" from the label and place it in the "location" object to be saved
=> Added Location notes to Add Device

BEIMA.Backend/MongoService/EnumServerType.cs, BEIMA.Backend/MongoService/MongoConnector.cs, BEIMA.Backend/StorageService/MinioStorageProvider.cs
Closes #459
Closes #460
Added parsing for:
DeployMongoConnection
MinioDeployHost
when the current env is set to "deploy" in local.settings.json
=> updated for deploy config

BEIMA.Client/src/pages/Devices/DevicesPage.js, BEIMA.Client/src/services/AllDevicesReport.js
Closes #457
Created the service function to get the bytes from the backend and download it as "All Devices" zip. For demoing purposes, I added a button so show how that would look like
https://user-images.githubusercontent.com/58532471/163689896-c5d654b5-45c7-44e3-ad8d-7bf3b1206d88.mp4
=> csv report js service

BEIMA.Client/src/pages/Users/UserPage.js, BEIMA.Client/src/pages/Users/UserPage.module.css, BEIMA.Client/src/shared/DropDown/FilledDropDown.js
Closes #421 
This PR implements using a dropdown for the Role instead of a textbox. It also implements the ability to disable a FilledDropDown as well.
=> Update UserPage to use dropdown for role

BEIMA.Client/src/services/AllDevicesReport.js
Closes #486
This was the last js service that needed an auth header. I added a quick button to test it and it does work correctly when a user is logged in
=> Last js service that needed headers

BEIMA.Client/src/pages/Authentication/LoginPage.js, BEIMA.Client/src/services/DeleteBuilding.js, BEIMA.Client/src/services/DeleteDevice.js, BEIMA.Client/src/services/DeleteDeviceType.js, BEIMA.Client/src/services/DeleteUser.js
Closes #496 
In order for the delete functions to work, there needs to be a null body, or it thinks the header is the body and the API will return a 401 and the user will get logged out. Added a null body to all the delete functions
=> adding null body for delete functions

BEIMA.Client/cypress/integration/DevicesPage.spec.js, BEIMA.Client/src/pages/Devices/DevicesPage.js, BEIMA.Client/src/pages/Devices/DevicesPage.module.css, BEIMA.Client/src/services/AllDevicesReport.js
Closes #418
Adds a button to the devices page that can call the generate all devices report endpoint in order to produce a zip file.
=> Added button to call all devices report endpoint

BEIMA.Client/src/pages/Users/UserPage.js
Closes #455 
This PR implements the ability to update passwords.
=> Allow admin to update passwords

BEIMA.Client/package.json
Closes #506
set the mapbox version to be fixed at 1.13.2
=> set mapbox version to 1.13.2

BEIMA.Backend/StorageService/StorageProvider.cs
Closes #512
Fixed StorageProvider.cs conditional statement to detect the deployed state
=> Images save to cloud provider when deployed

BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js, BEIMA.Client/src/services/GetDeviceTypeList.js
=> Adding count attribute to device type list and device type view page

BEIMA.Client/src/pages/Building/BuildingList.module.css, BEIMA.Client/src/pages/DeviceTypes/DeviceTypesPage.module.css, BEIMA.Client/src/pages/Devices/DevicesPage.module.css, BEIMA.Client/src/pages/Users/ListUsersPage.js, BEIMA.Client/src/pages/Users/ListUsersPage.module.css, BEIMA.Client/src/shared/FormList/FormListWithErrorFeedback.js
Closes #522 
This PR adds bottom margin to all the List pages (Device, DeviceType, Building, User). It also fixes the password input field on the Add New User page, as well as the Add New User button.
=> Add bottom margin to list pages

BEIMA.Client/src/pages/Building/AddBuildingPage.js, BEIMA.Client/src/pages/Building/BuildingPage.js, BEIMA.Client/src/pages/Devices/AddDevicePage.js
Bugs found while writing the building section of our user manual. Also applied them to other places where needed
=> Bugs found buildings

BEIMA.Backend.FT/ReportFT.cs, BEIMA.Backend.Test/ReportFunctions/AllDevicesReportTest.cs, BEIMA.Backend.Test/ReportService/ReportServiceTest.cs, BEIMA.Backend/ReportFunctions/AllDevicesReport.cs, BEIMA.Backend/ReportService/ReportWriter.cs
Closes #420
Updated report writer to use building name instead of building id. Also uses the device type name instead of device type id.
=> 420 all devices report building name

docker-compose.yaml
Closes #520
removed unneeded networking components, adopted dynamic host port mapping as suggested
=> updated ports and networking components

BEIMA.Client/package.json
Closes #417
Fixed the issue I was having with the package.json not aligning with the branch correctly. The method for changing the serving location was also changed since the ' homepage: "." ' var was not working on my local reverse proxy test
=> Task#417 add prod var to build

README.md
Closes #117
This PR adds info to our README. I added what Tom put for our project description on the github.io page, and wrote up some information about our tech stack as well. Feel free to suggest other items to put into the README.
=> Update README with useful info

BEIMA.Backend/Rules.cs
Closes #528 
Adds null checks on properties to the Rules logic.
=> Add null checks to Rules

BEIMA.Client/src/pages/Maps/MapPage.js
Closes #531
The map wasn't updating/rendering properly when we would try to rotate it, this should fix that.
=> Re-render map on rotate

docker-compose.yaml
Closes #535 
Added identifiers to the compose file so that ports for each service can be specified at run time on the host
=> added identifiers to host ports for each service

.github/workflows/deploy-client.yaml, BEIMA.Client/package.json, BEIMA.Client/public/web.config, BEIMA.Client/src/App.js
Hopefully fixes path issues when deployed to sdp server.
The App.js <BroswerRouter basename.... change makes it so that react know that /beima should the base route instead of root when trying to figure out what page to serve. The package.json change is to make it so we use the env file's public_url value so that we can have different ones for the running on sdp vs running on azure. The public_url is what tells relative location of where the files in the public folder are located.
=> Bug fix public url

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/FunctionalTestBase.cs
Closes #542
Adds the beima url prefix to the backend FT
=> Added beima prefix to FT

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/FunctionalTestBase.cs, BEIMA.Backend/host.json, docker-compose.yaml, proxy/Dockerfile, proxy/nginx.conf
Closes #540 
Added host.json change. Tested working without the "-service" on the end of the api calls over the network
=> added host.json change

BEIMA.Backend.Test/ReportService/ReportServiceTest.cs, BEIMA.Backend/BEIMA.Backend.csproj, BEIMA.Backend/ReportService/ReportWriter.cs
Fixes a bug where downloading a zip file from the backend running on a linux box was causing the zip to be unopenable without using 7zip. This had to do with the file names inside the zip. Also fixed an issue where commas and quotes were not properly being escaped which resulted in ill formatted rows.
=> Bug report writer
