BEIMA.Backend.Test/MongoConnectorTest.cs, BEIMA.Backend/MongoService/EnumServerType.cs, BEIMA.Backend/MongoService/MongoConnector.cs
Closes #23 - story
Closes #24 
Closes #26
Closes #27 
Closes #29 
Closes #60
This PR implements the MongoConnector. It abstracts out the basic CRUD operations we need for the "devices" collection. The purpose of this connector is only to abstract the calls to the MongoDB.Driver itself. In our endpoints, we still need to form the documents there; this connector will serve to accept those documents and perform those operations.
This story only concerns the "devices" collection. The "users" and "device-types" collections are not in this story's scope.
This PR also contains unit tests for the MongoConnector. All tests have passed on my local machine, and using the beima.yml GitHub Action.
I am aware this is a large pull request, but since all of this work is closely related, is an initial …
=> Database Service - Handle Devices Only

.github/workflows/beima.yml, BEIMA.Backend.Test/MongoService/MongoConnectorTest.cs, BEIMA.Backend.Test/UnitTestBase.cs, BEIMA.Backend/MongoService/MongoConnector.cs, BEIMA.DB.Schemas/building-schema.txt, BEIMA.DB.Schemas/device-schema.txt, BEIMA.DB.Schemas/device-type-schema.txt
Closes #81 - story
Closes #128 
Closes #129 
Closes #130 
Closes #131 
Closes #132 
Closes #132 
Closes #133
This PR implements DeviceType functionality in MongoConnector. It also implements the related unit tests, as well as the new environment variables in beima.yml. The code was mostly the same as the existing code for Device functionality, so it should look pretty similar.
There was also a change to the DB schemas. I removed the "deviceTypeId" and "buildingId" fields from the DeviceType and Building schemas respectively, since that would actually just be the "_id" field that is automatically generated when inserted into the database. I added the "_id" field to all of the schemas since that is what we will expect to see stored in the DB.
=> Implemented DeviceType Functionality in MongoConnector

BEIMA.Client/src/shared/ItemList/ItemList.js
Closes #300 
We needed to pass the boolean of isDeviceList throughout the ItemList file
=> Fixing missing title on Devices page

BEIMA.Client/cypress/integration/AddDevicePage.spec.js, BEIMA.Client/src/Constants.js, BEIMA.Client/src/pages/Devices/AddDevicePage.js, BEIMA.Client/src/pages/Devices/DevicePage.js, BEIMA.Client/src/shared/FormList/FormListWithErrorFeedback.js
Closes #297
In the add device page, if the year manufactured value contains any non-numeric chars, it will show an error message to the user and won't let the user add the device. When editing a device, the user will not be able to input any non-numeric values. 
The destination branch is Tom's PR, and there are many diffs because his branch isn't up to date with master. That's okay, we can wait for his PR to merge before we merge this one.
=> Force user to enter numeric value for year manufactured 

BEIMA.Backend/MongoService/MongoConnector.cs
Closes #327 
This PR abstracts out a lot of the basic CRUD calls in the MongoConnector. I realized that there does not need to be a separate implementation for each POCO, and it can all be abstracted. This will make adding on new MongoConnector functionality much easier in the future.
=> Refactor MongoConnector to abstract out basic CRUD calls

BEIMA.Backend.FT/BEIMA.Backend.FT.csproj, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.Test/DeviceFunctions/DeleteDeviceTest.cs, BEIMA.Backend.Test/DeviceFunctions/GetDeviceTest.cs, BEIMA.Backend/DeviceFunctions/DeleteDevice.cs, BEIMA.Backend/DeviceFunctions/GetDevice.cs
Closes #329
Closes #15
References #228 
Added the storage provider to the get and delete endpoints.
=> 329 add storage to get/delete device endpoints

BEIMA.Client/src/pages/Devices/AddDevicePage.js
Closes #168
when updating the text setter to a json object I neglected to update the check for no device type selected to match
=> fixed no device type selected warning on add device page

BEIMA.Backend.Test/MongoService/MongoConnectorTest.cs, BEIMA.Backend.Test/MongoService/MongoFilterGeneratorTest.cs, BEIMA.Backend/MongoService/MongoConnector.cs, BEIMA.Backend/MongoService/MongoFilterGenerator.cs
Closes #337 
This PR implements filtering functionality inside the MongoConnector. GetFilteredDevices was also implemented. 
It also abstracts out the Get method to use the GetFiltered method, since that is basically the same logic. The GetEqualsFilter method was also implemented to make retrieving a filter easier. All it does is return an "equals" filter given a key and value.
=> Implement filtering for Device in MongoConnector

BEIMA.Backend.Test/MongoService/MongoFilterGeneratorTest.cs, BEIMA.Backend/MongoService/MongoFilterGenerator.cs
Closes #360
This PR adds the ability to combine two separate filters into one filter. Essentially, it performs an AND operation on two filters to combine them together. Now, we will be able to match on multiple properties. 
For example:
username: "user1"
AND
password: "verysecurepassword!"
To use the CombineFilters method, you will need to first create two separate filters using the GetEqualsFilter method. Then, pass the two filters in to the CombineFilters method.
=> Add combine filter functionality in MongoFilterGenerator

BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.Test/DeviceFunctions/AddDeviceTest.cs, BEIMA.Backend.Test/DeviceFunctions/UpdateDeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/DeviceFunctions/AddDevice.cs, BEIMA.Backend/DeviceFunctions/UpdateDevice.cs
Closes #353
This adds the necessary validation onto the device endpoints to ensure that if a building id is provided, that it actually exists in the database.
=> Require valid or null building for devices

BEIMA.Backend.Test/MongoService/DeviceTest.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend/Models/Requests.cs, BEIMA.Backend/MongoService/Device.cs
Closes #299
This fixes the issue where we could not send an empty/null year manufactured value to the device endpoints. This was because the request parser was using regular int types instead of nullable int types. We should now be able to send empty/null year manufactured values.
=> Allow year manufactured to be null

BEIMA.Backend.Test/StorageService/AzureStorageProviderTest.cs, BEIMA.Backend.Test/StorageService/MinioStorageProviderTest.cs, BEIMA.Backend.Test/StorageService/StorageProviderTest.cs, BEIMA.Backend/DeviceFunctions/UpdateDevice.cs, BEIMA.Backend/StorageService/AzureStorageProvider.cs, BEIMA.Backend/StorageService/MinioStorageProvider.cs
Closes #358 
After investigation the delete(null) works fine when using the underlying azure methods, but would throw an exception when using the underlying minio methods. To remedy this, null/empty string validation was added to all of the storage provider methods.
=> 358 Bug adding photo null exception

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/TestData.cs, BEIMA.Backend.Test/UserFunctions/AddUserTest.cs, BEIMA.Backend/BEIMA.Backend.csproj, BEIMA.Backend/Models/Requests.cs, BEIMA.Backend/MongoService/IMongoConnector.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/Rules.cs, BEIMA.Backend/UserFunctions/AddUser.cs
Closes #302 
Closes #378
This PR implements the AddUser endpoint. It also implements a password hashing package called BCrypt.Net. This uses the bcrypt algorithm, and it is generally accepted as a secure password hashing algorithm. This package was chosen because it is widely used, and it makes password hashing extremely easy as shown in the documentation here: https://github.com/BcryptNet/bcrypt.net
Using statement: 
`using BCryptNet = BCrypt.Net.BCrypt;`
To hash passwords:
`string passwordHash = BCryptNet.HashPassword(data.Password);`
To check a plain text password against a hashed password:
`bool passwordCorrect = BCrypt.Verify("plaintextPassword1!", passwordHash);`
Note on EnhancedHashPassword and EnhancedVerify methods in BCrypt.Net:
A conscious decision was made to not use the …
=> User POST - AddUser

BEIMA.Client/src/pages/Devices/AddDevicePage.js
Closes #159
Moved confirmation that device type is selected to happen before trying to create JSON object
Added async to createJSON so the warning can be ignored
added check for isConfirmed from warning message to determine if save should still be attempted
=> Task#159 add device empty field warning

BEIMA.Backend.Test/RulesTest.cs, BEIMA.Backend/Resources.Designer.cs, BEIMA.Backend/Resources.resx, BEIMA.Backend/Rules.cs
Closes #294
This adds validation for device types to ensure that fields are formatted correctly.
=> Device type backend validation

BEIMA.Backend.Test/ReportService/ReportServiceTest.cs, BEIMA.Backend/Models/Reports.cs, BEIMA.Backend/ReportService/ReportWriter.cs
Closes #389
Adds a method to the report writer to allow it to generate a file containing a list of
all device types in the database as well as a count of how many devices are associated
with each device type.
=> ReportWriter: Device Type Report

BEIMA.Backend.FT/BeimaClient.cs, BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.Test/DeviceFunctions/GetDeviceListTest.cs, BEIMA.Backend/DeviceFunctions/GetDeviceList.cs
Closes #409
This adds the capability for us to use deviceType and building filters using the query string on the device list endpoint.
Example query string:
- localhost:7071/api/device-list?deviceType=aaaa&building=bbbb&building=cccc
This query would return the list of device with ```deviceTypeId 'aaaa' AND (buildingId 'bbbb' OR buildingId 'cccc')```
=> Add device list endpoint filters

BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js, BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.module.css, BEIMA.Client/src/pages/Devices/DevicePage.js, BEIMA.Client/src/pages/Devices/DevicePage.module.css, BEIMA.Client/src/shared/ItemCard/ItemCard.js, BEIMA.Client/src/shared/ItemCard/ItemCard.module.css, BEIMA.Client/src/shared/ItemList/ItemList.js, BEIMA.Client/src/shared/ItemList/ItemList.module.css
Closes #217 
Add ability to expand field tile in order to see all of the text on the device and device type pages. When not expanded the input will show "fieldtext..." Additionally fix some css issues on the device and device type list view that would hide the details button when title of an item was very long.
=> #217 Indicate More Tile Data

BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js
Closes #162 
warns on empty notes and description, allows without prompt when both present, warns when either one are missing
=> Device Type page - Added warning for blank editable fields

BEIMA.Backend.FT/AuthFT.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/AuthFunctions/LoginTest.cs, BEIMA.Backend.Test/UserFunctions/AddUserTest.cs, BEIMA.Backend.Test/UserFunctions/UpdateUserTest.cs, BEIMA.Backend/AuthFunctions/Login.cs, BEIMA.Backend/UserFunctions/AddUser.cs, BEIMA.Backend/UserFunctions/UpdateUser.cs
Closes #403
This PR implements case insensitivity for usernames. This involved modifying the AddUser, UpdateUser, and Login endpoints to handle case insensitivity.
=> Case insensitivity for usernames

BEIMA.Client/src/pages/Devices/DevicePage.js
Closes #160
Added warnings for each empty field and converted text to capitalize/split the names of the empty fields so it's "Device Tag" instead of "deviceTag"
=> added warning and text formatting

BEIMA.Backend.FT/DeviceFT.cs, BEIMA.Backend.FT/FunctionalTestBase.cs, BEIMA.Backend.FT/UserFT.cs, BEIMA.Backend.Test/UserFunctions/AddUserTest.cs, BEIMA.Backend.Test/UserFunctions/DeleteUserTest.cs, BEIMA.Backend.Test/UserFunctions/GetUserListTest.cs, BEIMA.Backend.Test/UserFunctions/GetUserTest.cs, BEIMA.Backend.Test/UserFunctions/UpdateUserTest.cs, BEIMA.Backend/AuthService/IAuthenticationService.cs, BEIMA.Backend/Constants.cs, BEIMA.Backend/DeviceFunctions/AddDevice.cs, BEIMA.Backend/MongoService/MongoConnector.cs, BEIMA.Backend/UserFunctions/AddUser.cs, BEIMA.Backend/UserFunctions/DeleteUser.cs, BEIMA.Backend/UserFunctions/GetUser.cs, BEIMA.Backend/UserFunctions/GetUserList.cs, BEIMA.Backend/UserFunctions/UpdateUser.cs
Closes #408
This adds authentication to all of the user endpoints. This also updates the application to create a default admin user on startup of the backend via the mongo connector if an admin user does not exist in the current database. The functional tests have also been updated to adapt to this change.
=> User endpoint authentication

BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.FT/TestObjects.cs, BEIMA.Backend.Test/DeviceTypeFunctions/GetDeviceTypeTest.cs, BEIMA.Backend/DeviceTypeFunctions/GetDeviceType.cs
Closes #410
This PR implements including the Count in the return object for GetDeviceType. Basically, this count is referring to the number of Devices that are currently in the "devices" collection, with this specific DeviceTypeId being used.
=> Add count to return object for GetDeviceType endpoint

BEIMA.Client/src/pages/Devices/AddDevicePage.js
Closes #475
When we change the device type when trying to add a device, the custom fields from the previously selected device type are not shown anymore.
=> Clearing previous custom fields when the device type changes

BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js
Closes #463
Added capitalization to fields names on warning messages
Now it's:
instead of
=> added capitalization to warnings

BEIMA.Backend.FT/DeviceTypeFT.cs, BEIMA.Backend.Test/DeviceTypeFunctions/AddDeviceTypeTest.cs, BEIMA.Backend.Test/DeviceTypeFunctions/DeleteDeviceTypeTest.cs, BEIMA.Backend.Test/DeviceTypeFunctions/GetDeviceTypeListTest.cs, BEIMA.Backend.Test/DeviceTypeFunctions/GetDeviceTypeTest.cs, BEIMA.Backend.Test/DeviceTypeFunctions/UpdateDeviceTypeTest.cs, BEIMA.Backend/DeviceTypeFunctions/AddDeviceType.cs, BEIMA.Backend/DeviceTypeFunctions/DeleteDeviceType.cs, BEIMA.Backend/DeviceTypeFunctions/GetDeviceType.cs, BEIMA.Backend/DeviceTypeFunctions/GetDeviceTypeList.cs, BEIMA.Backend/DeviceTypeFunctions/UpdateDeviceType.cs
Closes #406
Adds authentication to the device type endpoints. I also set some of the endpoints to use GetFilteredDevices instead of GetAllDevices where appropriate.
=> Device type endpoint authentication

BEIMA.Backend.FT/BuildingFT.cs, BEIMA.Backend.Test/BuildingFunctions/AddBuildingTest.cs, BEIMA.Backend.Test/BuildingFunctions/DeleteBuildingTest.cs, BEIMA.Backend.Test/BuildingFunctions/GetBuildingListTest.cs, BEIMA.Backend.Test/BuildingFunctions/GetBuildingTest.cs, BEIMA.Backend.Test/BuildingFunctions/UpdateBuildingTest.cs, BEIMA.Backend/BuildingFunctions/AddBuilding.cs, BEIMA.Backend/BuildingFunctions/DeleteBuilding.cs, BEIMA.Backend/BuildingFunctions/GetBuilding.cs, BEIMA.Backend/BuildingFunctions/GetBuildingList.cs, BEIMA.Backend/BuildingFunctions/UpdateBuilding.cs
Closes #407 
Adds authentication to the front of all the building functions as well as updates the last modified user to use the username in the claims token for the add and update building endpoint.
=> #407 building endpoint auth

BEIMA.Backend/Dockerfile, BEIMA.Client/Dockerfile
Closes #492
Moving the file copy directives for the API to the end of the Dockerfile will allow cached build stages to be used when files are changed for the backend since the software to run the API does not need to be reinstalled every time
Need to set the telemetry bit to keep MS from snooping
moving the package list files only before the rest of the source allows cached layers to be used for the front end if no packages have changed (cuts out long "npm i" time)
=> changed build order in docker containers to leverage cached layers

BEIMA.Client/src/pages/DeviceTypes/AddDeviceTypePage.js, BEIMA.Client/src/shared/FormList/FormList.js, BEIMA.Client/src/shared/FormList/FormListWithErrorFeedback.js
Closes #446
This PR implements having text inputs wrap when there is too much text. Essentially, I replaced all those fields with textareas, and users will be able to scroll and manually expand the textarea when they need more room.
This PR also fixes a bug with the custom field input on AddDeviceTypePage. The "fields" variable was not using a state variable, so it has been updated to use useState().
=> Wrap text when text overflows

.github/workflows/deploy-client.yaml
Closes #504
Adds the env client variable so that we can access the map api key on the deployed server.
=> Add api key to env for build/deploy

docker-compose.yaml
Closes #508
MongoDb and Minio are accessed via network name or IP, they do not need to use the host network so their binding has ben removed
=> removed unneeded port bindings to host machine

BEIMA.Client/src/pages/Building/BuildingPage.js, BEIMA.Client/src/pages/DeviceTypes/DeviceTypePage.js
Closes #515 
This PR implements dynamic reload after an edit on the DeviceType and Building pages.
=> Dynamic reload on edit DeviceType and Building

.dockerignore
Closes #434 
the data dir has files with permissions based on the container, if docker-compose tries to access it at build time permission will be denied and it will halt the build
=> added dockerignore and populated with data dir
